on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  multi_event:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Basic Information"
        run: |
          echo "REF: $GITHUB_REF"
          echo "Job ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
          echo "Repos: $GITHUB_REPOSITORY"
          echo "Github api url: $GITHUB_API_URL"